name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Start local node
        run: npx hardhat node --port 8545 --hostname 0.0.0.0 &

      - name: Deploy contracts
        run: npx hardhat ignition deploy ./ignition/modules/Store.js

      - name: Run tests
        run: npx hardhat test

  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Start local node
        run: npx hardhat node --port 8545 --hostname 0.0.0.0 &

      - name: Run coverage
        run: npx hardhat coverage
